---
name: Build and Push docker image to DockerHub Registry
on:
  push:
    branches: [ "main" ]
    # paths:
    #   - 'app/**'
    #   - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]

jobs:
  #Stage build docker image
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pyhton-flask-webapp:$(date +%s)
      
  #Stage Deploy docker image
  deploy:
    name: Deploy docker image to DockerHub Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: Deploy
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{username}}/pyhton-flask-webapp:latest
...
