---
name: Build and Push docker image to DockerHub Registry
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: python-flask-webapp  # Update the image name here
  IMAGE_TAG: latest #$(date +%s)
 
    
jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

      - name: Run and test docker container
        #continue-on-error: true  # Continue ci execution when job failed with errors
        run: |
          # Run the container in detached mode and test its behavior
          docker run -d --rm --name ${{ env.IMAGE_NAME }}_container -p 5000:5000 ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
          # Add a delay to give the container time to start
          sleep 5
        
          # Check the container logs to verify it's running
          docker logs ${{ env.IMAGE_NAME }}_container
        
          # Make an HTTP request to the exposed port
          curl http://localhost:5000

  deploy:
    needs: build_and_run
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME}} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{env.IMAGE_TAG}}