---
name: Build and Push docker image to DockerHub Registry
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: pyhton-flask-webapp
  
jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up Docker
    #   uses: docker/setup-docker@v2
    #   with:
    #     dockerfile: Dockerfile

    - name: Build docker image
      run: docker build . --file Dockerfile --tag $(IMAGE_NAME):$(date +%s)

    - name: Run docker container
      run: |
        # run the container and test its behavior
        docker run --rm --name $(IMAGE_NAME):$(date +%s) curl http://localhost:5000
        
  deploy:
    needs: build_and_run
    runs-on: ubuntu-latest

    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push to DockerHub Registry
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/$(IMAGE_NAME):latest
